--Base Infrastructure Setup

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS TASK11;
CREATE SCHEMA IF NOT EXISTS TASK11.PAGILA_RAWS;
CREATE SCHEMA IF NOT EXISTS TASK11.SAKILA_RAWS;

CREATE WAREHOUSE IF NOT EXISTS AIRBYTE_WH 
    WITH WAREHOUSE_SIZE = 'XSMALL' 
    AUTO_SUSPEND = 60;

--Airbyte Role & Permissions (Full Access)

CREATE ROLE IF NOT EXISTS AIRBYTE_ROLE;

GRANT ALL PRIVILEGES ON DATABASE TASK11 TO ROLE AIRBYTE_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE TASK11 TO ROLE AIRBYTE_ROLE;
GRANT USAGE ON WAREHOUSE AIRBYTE_WH TO ROLE AIRBYTE_ROLE;

CREATE USER IF NOT EXISTS AIRBYTE_USER 
    PASSWORD = 'airbyte' 
    DEFAULT_ROLE = AIRBYTE_ROLE;
    
GRANT ROLE AIRBYTE_ROLE TO USER AIRBYTE_USER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA TASK11.PAGILA_RAWS TO ROLE AIRBYTE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA TASK11.SAKILA_RAWS TO ROLE AIRBYTE_ROLE;

--Airflow Dev Role (verification)

CREATE ROLE IF NOT EXISTS AIRFLOW_DEV_ROLE;

GRANT USAGE ON WAREHOUSE AIRBYTE_WH TO ROLE AIRFLOW_DEV_ROLE; 
GRANT USAGE ON DATABASE TASK11 TO ROLE AIRFLOW_DEV_ROLE;
GRANT USAGE ON SCHEMA TASK11.PAGILA_RAWS TO ROLE AIRFLOW_DEV_ROLE;
GRANT USAGE ON SCHEMA TASK11.SAKILA_RAWS TO ROLE AIRFLOW_DEV_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA TASK11.PAGILA_RAWS TO ROLE AIRFLOW_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA TASK11.SAKILA_RAWS TO ROLE AIRFLOW_DEV_ROLE;


GRANT ROLE AIRFLOW_DEV_ROLE TO USER CURRENT_USER();